# Generated by Django 5.0.2 on 2024-06-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_alter_account_id_alter_adoption_id_alter_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='subject_areas',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='website_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
