# Generated by Django 5.0.2 on 2024-06-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0005_alter_contact_adoption_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opportunity",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
