# Generated by Django 5.0.2 on 2024-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0006_alter_opportunity_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="subject_interest",
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Subject Interest"),
        ),
    ]
