# Generated by Django 5.0.2 on 2025-03-10 15:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0010_alter_contact_accounts_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="local_create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Local Create Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="account",
            name="local_update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Local Update Date"),
        ),
        migrations.AddField(
            model_name="adoption",
            name="local_create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Local Create Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="adoption",
            name="local_update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Local Update Date"),
        ),
        migrations.AddField(
            model_name="book",
            name="local_create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Local Create Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="book",
            name="local_update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Local Update Date"),
        ),
        migrations.AddField(
            model_name="contact",
            name="local_create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Local Create Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="local_update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Local Update Date"),
        ),
        migrations.AddField(
            model_name="opportunity",
            name="local_create_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now, verbose_name="Local Create Date"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="opportunity",
            name="local_update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="Local Update Date"),
        ),
    ]
