coverage:
  status:
    patch: true
    project: false
comment: false
ignore:
  - "*tests.py"
  - 'healthcheck/*'
  - 'manage.py'
  - '*/migrations/*'
  - '*settings.py'
  - '*wsgi.py'
  - '*asgi.py'
