coverage:
  status:
    patch:
      default:
        target: 80%
    project:
      default:
        target: 80%
comment: false
ignore:
  - "*tests.py"
  - "tests/*"
  - 'manage.py'
  - '*/migrations/*'
  - '*/settings/*'
  - '*wsgi.py'
  - '*asgi.py'
