# Generated by Django 5.0.2 on 2024-06-08 21:17

import django.db.models.deletion
import django.db.models.manager
import salesforce.fields
from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=255, verbose_name='Account Name')),
                ('type', salesforce.fields.CharField(blank=True, choices=[('College/University (4)', 'College/University (4)'), ('Technical/Community College (2)', 'Technical/Community College (2)'), ('Career School/For-Profit (2)', 'Career School/For-Profit (2)'), ('For-Profit Tutoring', 'For-Profit Tutoring'), ('High School', 'High School'), ('Elementary School', 'Elementary School'), ('Middle/Junior High School', 'Middle/Junior High School'), ('K-12 School', 'K-12 School'), ('Other', 'Other'), ('Research Centers', 'Research Centers'), ('Intergovernmental', 'Intergovernmental'), ('Tutoring', 'Tutoring'), ('Programs', 'Programs'), ('Vendors', 'Vendors'), ('School District', 'School District'), ('Home School', 'Home School'), ('Parent', 'Parent'), ('Vocational', 'Vocational'), ('Child', 'Child')], db_column='Type', max_length=255, null=True, verbose_name='Account Type')),
                ('city', salesforce.fields.CharField(blank=True, db_column='BillingCity', max_length=40, null=True)),
                ('state', salesforce.fields.CharField(blank=True, db_column='BillingState', max_length=80, null=True)),
                ('country', salesforce.fields.CharField(blank=True, db_column='BillingCountry', max_length=80, null=True)),
                ('state_code', salesforce.fields.CharField(blank=True, db_column='BillingStateCode', max_length=10, null=True)),
                ('country_code', salesforce.fields.CharField(blank=True, db_column='BillingCountryCode', default='US', max_length=10, null=True)),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate', null=True)),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate', null=True)),
                ('last_activity_date', salesforce.fields.DateField(blank=True, db_column='LastActivityDate', null=True, verbose_name='Last Activity')),
                ('lms', salesforce.fields.CharField(blank=True, choices=[('Blackboard', 'Blackboard'), ('Brightspace', 'Brightspace'), ('Canvas', 'Canvas'), ('D2L (Desire2Learn)', 'D2L (Desire2Learn)'), ('Learning Studio', 'Learning Studio'), ('Moodle', 'Moodle'), ('MoodleRooms', 'MoodleRooms'), ('Sakai', 'Sakai'), ('Other', 'Other')], db_column='LMS__c', max_length=255, null=True, verbose_name='LMS')),
                ('books_adopted', salesforce.fields.TextField(blank=True, db_column='Books_Adopted__c', null=True, verbose_name='Books Adopted')),
                ('sheer_id_school_name', salesforce.fields.CharField(blank=True, db_column='SheerID_School_Name__c', max_length=255, null=True, verbose_name='SheerID School Name')),
                ('ipeds_id', salesforce.fields.CharField(blank=True, db_column='IPEDS_ID__c', max_length=255, null=True, verbose_name='IPEDS ID')),
                ('nces_district_id', salesforce.fields.CharField(blank=True, db_column='NCES_District_ID__c', max_length=50, null=True)),
                ('nces_district_id2', salesforce.fields.CharField(blank=True, db_column='NCES_District_ID2__c', max_length=1300, null=True)),
                ('nces_id', salesforce.fields.CharField(blank=True, db_column='NCESID__c', max_length=255, null=True, verbose_name='NCESID')),
            ],
            options={
                'verbose_name': 'School',
                'verbose_name_plural': 'Schools',
                'db_table': 'Account',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(max_length=255)),
                ('official_name', salesforce.fields.CharField(db_column='Official_Name__c', max_length=255)),
                ('type', salesforce.fields.CharField(db_column='Book_Type__c', max_length=255)),
                ('subject_areas', salesforce.fields.CharField(db_column='Subject_Area__c', max_length=255)),
                ('website_url', salesforce.fields.URLField(db_column='OSC_URL__c', max_length=255)),
                ('active_book', salesforce.fields.BooleanField(db_column='Active__c', default=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'Book__c',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', salesforce.fields.CharField(db_column='Subject', max_length=255, verbose_name='Subject')),
                ('description', salesforce.fields.TextField(db_column='Description', verbose_name='Description')),
                ('product', salesforce.fields.CharField(blank=True, db_column='Product__c', max_length=255, null=True, verbose_name='Product')),
                ('feature', salesforce.fields.CharField(blank=True, db_column='Feature__c', max_length=255, null=True, verbose_name='Feature')),
                ('issue', salesforce.fields.CharField(blank=True, db_column='Issue__c', max_length=255, null=True, verbose_name='Issue')),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'db_table': 'Case',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', salesforce.fields.CharField(db_column='FirstName', max_length=255)),
                ('last_name', salesforce.fields.CharField(db_column='LastName', max_length=255)),
                ('full_name', salesforce.fields.CharField(db_column='Name', max_length=255)),
                ('email', salesforce.fields.EmailField(db_column='Email', max_length=255)),
                ('role', salesforce.fields.CharField(db_column='Role__c', max_length=255)),
                ('position', salesforce.fields.CharField(db_column='Position__c', max_length=255)),
                ('title', salesforce.fields.CharField(db_column='Title', max_length=128)),
                ('adoption_status', salesforce.fields.CharField(db_column='Adoption_Status__c', max_length=255)),
                ('adoptions_json', salesforce.fields.TextField(db_column='AdoptionsJSON__c')),
                ('verification_status', salesforce.fields.CharField(db_column='FV_Status__c', max_length=255)),
                ('reject_reason', salesforce.fields.CharField(db_column='Reject_Reason__c', max_length=255)),
                ('accounts_uuid', salesforce.fields.CharField(db_column='Accounts_UUID__c', max_length=255)),
                ('accounts_id', salesforce.fields.CharField(db_column='Accounts_ID__c', help_text='Prioritize using Accounts_UUID__c over this for ox accounts users.', max_length=255)),
                ('signup_date', salesforce.fields.DateTimeField(db_column='Signup_Date__c')),
                ('lead_source', salesforce.fields.CharField(db_column='LeadSource', max_length=255)),
                ('lms', salesforce.fields.CharField(db_column='LMS__c', max_length=255)),
                ('last_modified_date', salesforce.fields.DateTimeField(blank=True, db_column='LastModifiedDate', null=True, verbose_name='Last Modified Date')),
                ('subject_interest', salesforce.fields.CharField(blank=True, db_column='Subject_Interest__c', max_length=255, null=True, verbose_name='Subject Interest')),
                ('account', salesforce.fields.ForeignKey(blank=True, db_column='AccountId', null=True, on_delete=django.db.models.deletion.PROTECT, to='sf.account', verbose_name='Account ID')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'db_table': 'Contact',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type_id', salesforce.fields.CharField(blank=True, db_column='RecordTypeId', max_length=18, null=True, verbose_name='Record Type ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=120)),
                ('description', salesforce.fields.TextField(blank=True, db_column='Description', null=True)),
                ('stage_name', salesforce.fields.CharField(choices=[('Confirmed Adoption Won', 'Confirmed Adoption Won'), ('Closed Lost', 'Closed Lost'), ('Unconfirmed', 'Unconfirmed'), ('Lapsed - Book Used Previously Not Currently', 'Lapsed - Book Used Previously Not Currently'), ('Inactive - Book No Longer in Use', 'Inactive - Book No Longer in Use'), ('Assumed - Book Likely in Use', 'Assumed - Book Likely in Use'), ('Active - Book Currently in Use', 'Active - Book Currently in Use')], db_column='StageName', max_length=255, verbose_name='Stage')),
                ('amount', salesforce.fields.DecimalField(blank=True, db_column='Amount', decimal_places=2, max_digits=18, null=True, verbose_name='Savings: Current')),
                ('probability', salesforce.fields.DecimalField(blank=True, db_column='Probability', decimal_places=0, default=salesforce.fields.DefaultedOnCreate(), max_digits=3, null=True, verbose_name='Probability (%)')),
                ('close_date', salesforce.fields.DateField(db_column='CloseDate', help_text='IF Type = Renewal > Date this was renewed\r\nIF Type = Renewal Verified > Date this was verified\r\nIF Type = New Business > Date this was closed (won)', verbose_name='Confirm Date')),
                ('type', salesforce.fields.CharField(blank=True, choices=[('Renewal', 'Renewal'), ('New Business', 'New Business'), ('Renewal - Verified', 'Renewal - Verified')], db_column='Type', default='New Business', max_length=255, null=True, verbose_name='Opportunity Type')),
                ('lead_source', salesforce.fields.CharField(blank=True, choices=[('Customer Service Ticket', 'Customer Service Ticket'), ('Phone', 'Phone'), ('Chat', 'Chat'), ('Conference', 'Conference'), ('Comp Request', 'Comp Request'), ('Partner', 'Partner'), ('Newsletter', 'Newsletter'), ('Adoption Form', 'Adoption Form'), ('Referral Form', 'Referral Form'), ('Renewal Form', 'Renewal Form'), ('Donation', 'Donation'), ('Web', 'Web'), ('Webinar', 'Webinar'), ('Institutional Relations', 'Institutional Relations'), ('Followup Form', 'Followup Form'), ('Student', 'Student'), ('Email', 'Email'), ('Tutor Signup', 'Tutor Signup'), ('Interest Form', 'Interest Form'), ('Rover', 'Rover'), ('Testimonial', 'Testimonial'), ('Renewal Popup', 'Renewal Popup'), ('Partner Marketplace', 'Partner Marketplace'), ('Offsite Go-To-Webinar Form', 'Offsite Go-To-Webinar Form'), ('Website Tutor Webinar Form', 'Website Tutor Webinar Form'), ('Offsite Creator Feast Registration Form', 'Offsite Creator Feast Registration Form'), ('Manual List Adds', 'Manual List Adds'), ('Website E-Newsletter Sign-Up Form', 'Website E-Newsletter Sign-Up Form'), ('Website Institutional Partner Sign Up Form', 'Website Institutional Partner Sign Up Form'), ('Website Contact Us Form', 'Website Contact Us Form'), ('TSR', 'TSR'), ('Facebook Ads', 'Facebook Ads'), ('LinkedIn Ads', 'LinkedIn Ads'), ('BMG Import', 'BMG Import'), ('Account Creation', 'Account Creation')], db_column='LeadSource', max_length=255, null=True)),
                ('is_closed', salesforce.fields.BooleanField(db_column='IsClosed', default=False, verbose_name='Closed')),
                ('is_won', salesforce.fields.BooleanField(db_column='IsWon', default=False, verbose_name='Won')),
                ('owner_id', salesforce.fields.CharField(db_column='OwnerId', default=salesforce.fields.DefaultedOnCreate(), max_length=18, verbose_name='Owner ID')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('created_by_id', salesforce.fields.CharField(db_column='CreatedById', max_length=18, verbose_name='Created By ID')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('last_modified_by_id', salesforce.fields.CharField(db_column='LastModifiedById', max_length=18, verbose_name='Last Modified By ID')),
                ('system_modstamp', salesforce.fields.DateTimeField(db_column='SystemModstamp')),
                ('last_activity_date', salesforce.fields.DateField(blank=True, db_column='LastActivityDate', null=True, verbose_name='Last Activity')),
                ('last_activity_in_days', salesforce.fields.IntegerField(blank=True, db_column='LastActivityInDays', null=True, verbose_name='Recent Activity')),
                ('last_stage_change_date', salesforce.fields.DateTimeField(blank=True, db_column='LastStageChangeDate', null=True)),
                ('last_stage_change_in_days', salesforce.fields.IntegerField(blank=True, db_column='LastStageChangeInDays', null=True, verbose_name='Days In Stage')),
                ('fiscal_year', salesforce.fields.IntegerField(blank=True, db_column='FiscalYear', null=True)),
                ('fiscal', salesforce.fields.CharField(blank=True, db_column='Fiscal', max_length=6, null=True, verbose_name='Fiscal Period')),
                ('last_viewed_date', salesforce.fields.DateTimeField(blank=True, db_column='LastViewedDate', null=True)),
                ('last_referenced_date', salesforce.fields.DateTimeField(blank=True, db_column='LastReferencedDate', null=True)),
                ('account', salesforce.fields.ForeignKey(blank=True, db_column='AccountId', max_length=18, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sf.account', verbose_name='Account ID')),
                ('book', salesforce.fields.ForeignKey(blank=True, db_column='Book__c', max_length=18, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sf.book')),
                ('contact', salesforce.fields.ForeignKey(blank=True, db_column='ContactId', max_length=18, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sf.contact', verbose_name='Contact ID')),
            ],
            options={
                'verbose_name': 'Opportunity',
                'verbose_name_plural': 'Opportunities',
                'db_table': 'Opportunity',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_number', salesforce.fields.CharField(db_column='Name', max_length=80)),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('system_modstamp', salesforce.fields.DateTimeField(db_column='SystemModstamp')),
                ('last_activity_date', salesforce.fields.DateField(blank=True, db_column='LastActivityDate', null=True)),
                ('class_start_date', salesforce.fields.DateField(blank=True, db_column='Class_Start_Date__c', null=True)),
                ('confirmation_date', salesforce.fields.DateField(blank=True, db_column='Confirmation_Date__c', null=True)),
                ('name', salesforce.fields.CharField(blank=True, db_column='Name__c', max_length=255, null=True)),
                ('base_year', salesforce.fields.DecimalField(blank=True, db_column='Base_Year__c', decimal_places=0, max_digits=4, null=True)),
                ('adoption_type', salesforce.fields.CharField(choices=[('Faculty/Teacher Adoption', 'Faculty/Teacher Adoption'), ('School Adoption', 'School Adoption')], db_column='Adoption_Type__c', max_length=255, verbose_name='Adoption Type')),
                ('students', salesforce.fields.DecimalField(blank=True, db_column='Students__c', decimal_places=0, max_digits=18, null=True)),
                ('school_year', salesforce.fields.CharField(db_column='School_Year__c', max_length=9, verbose_name='School Year')),
                ('terms_used', salesforce.fields.CharField(blank=True, choices=[('Fall', 'Fall'), ('Spring', 'Spring'), ('Both', 'Both'), ('Winter', 'Winter'), ('Summer', 'Summer')], db_column='Terms_Used__c', max_length=255, null=True, verbose_name='Terms Used')),
                ('confirmation_type', salesforce.fields.CharField(choices=[('OpenStax Confirmed Adoption', 'OpenStax Confirmed Adoption'), ('Third Party Confirmed Adoption', 'Third Party Confirmed Adoption'), ('User Behavior Informed Adoption', 'User Behavior Informed Adoption')], db_column='Confirmation_Type__c', default='OpenStax Confirmed Adoption', max_length=255, verbose_name='Confirmation Type')),
                ('how_using', salesforce.fields.CharField(blank=True, choices=[('As the core textbook for my course', 'As the core textbook for my course'), ('As an optional/recommended textbook for my course', 'As an optional/recommended textbook for my course'), ('To teach, tutor, or support students outside of a course setting', 'To teach, tutor, or support students outside of a course setting'), ('For my own knowledge or other work', 'For my own knowledge or other work')], db_column='How_Using__c', max_length=255, null=True, verbose_name='How Using')),
                ('savings', salesforce.fields.DecimalField(blank=True, db_column='Savings__c', decimal_places=2, max_digits=18, null=True)),
                ('contact', salesforce.fields.ForeignKey(db_column='Opportunity__r.Contact__c', on_delete=django.db.models.deletion.DO_NOTHING, to='sf.contact')),
                ('opportunity', salesforce.fields.ForeignKey(db_column='Opportunity__c', max_length=18, on_delete=django.db.models.deletion.DO_NOTHING, to='sf.opportunity')),
            ],
            options={
                'verbose_name': 'Adoption',
                'verbose_name_plural': 'Adoptions',
                'db_table': 'Adoption__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
